name: 'Read keyvault secrets'
description: 'Read keyvault secrets and returns hash map of key value pairs'

inputs:
  KEY_ARRAY:
    description: 'array of keys whose value we want to read'
    required: true
  KEYVAULT_NAME:
    description: 'the keyvault name to use'
    required: true
      
runs:
  using: "composite"
  steps:
    - name: 'Read Secrets from keyvault'
      shell: pwsh
      run: |
        .\.github\scripts\keyvault.ps1 -array @${{ inputs.KEY_ARRAY }} -vaultName ${{ inputs.KEYVAULT_NAME }}
