#This docker builds a container for the LoRa Base station

FROM debian
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y --no-install-recommends apt-utils build-essential
RUN git clone https://github.com/lorabasics/basicstation.git
WORKDIR /basicstation
RUN cd examples/live-s2.sm.tc && rm -rf cups*
RUN make platform=linux variant=std
COPY start_basestation_amd64.sh .
ENTRYPOINT ["./start_basestation_amd64.sh"]
