#This docker builds a container for the LoRa Base station

FROM arm32v7/debian:stretch-slim
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y --no-install-recommends apt-utils build-essential
RUN git clone https://github.com/lorabasics/basicstation.git
WORKDIR /basicstation
RUN cd examples/live-s2.sm.tc && rm -rf cups*
RUN make platform=rpi variant=std
COPY start_basestation.sh .
ENTRYPOINT ["./start_basestation.sh"]
