# action.yml
name: 'IoT Edge Dev'
description: 'Iot Edge cli'
inputs:
  command:
    description: 'The command to run'
    required: true
  file_name:
    description: 'File path of the manifest file'
    required: true
  folder_path:
    description: 'Folder path of the manifest file'
    required: true
  target_platform: 
    description: 'Platform to target'
    required: false
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.folder_path }}
    - ${{ inputs.file_name }}
    - ${{ inputs.target_platform }}
