version: 2
updates:
  # Maintain dependencies the LoRa Engine
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for universal decoder
  - package-ecosystem: "npm"
    directory: "/Samples/UniversalDecoder"
    schedule:
      interval: "daily"
  # Maintain dependencies for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
