site_name: IoTEdge LoRaWAN StarterKit - documentation
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    # - navigation.expand
    - navigation.tracking
    - search.suggest
    - search.highlight
   # - header.autohide
   # - toc.integrate

repo_url: https://github.com/Azure/iotedge-lorawan-starterkit
edit_uri: edit/docs/main/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - abbr
  - pymdownx.snippets
  - meta
  - toc
  - mdx_truly_sane_lists

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      fallback_to_build_date: true

extra_css:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

nav:
  - index.md
  - quickstart.md
  - 'User Guide':
    - user-guide/devguide.md
    - user-guide/partner.md
    - user-guide/upgrade.md
    - user-guide/documentation.md
    - user-guide/observability.md
    - 'Basic Station configuration':
      - user-guide/station-device-provisioning.md
      - user-guide/station-authentication-modes.md
      - user-guide/station-module-configuration.md
    - 'Region specifics':
      - user-guide/as923.md
    - Testing:
      - user-guide/testing/e2e_tests.md
      - user-guide/testing/integration_tests.md
  - 'Reference':
    - user-guide/architecture.md
    - user-guide/message-flows.md
    - user-guide/caching.md
    - user-guide/ci-setup.md
  - 'Samples':
    - samples/arduino.md
    - 'Decoders':
      - samples/decoders/decoder.md
      - samples/decoders/universal.md
      - samples/decoders/cayenne.md
  - Tools:
    - tools/device-provisioning.md
    - tools/arduino-samples.md
  - 'Decision Log':
    - adr/001_region_cn470_implementation.md
    - adr/002_lbs_configuration.md
    - adr/003_documentation.md
    - adr/004_region_as923_implementation.md
    - adr/005_observability.md
    - adr/006_cups.md
    - adr/007_message_deduplication.md
  - About:
    - 'Known Issues': issues.md
    - 'Support': support.md
    - 'Contributing': contributing.md
    - 'License': 'license.md'

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Azure/iotedge-lorawan-starterkit
      name: iotedge-lorawan-starterkit on GitHub

