# DisableDockerDetector "Users should have the possibility to build the docker image locally. The CI build will use the docker image from our internal registry. See ./.github/workflows/ci.yml for more information."
ARG SOURCE_CONTAINER_REGISTRY_ADDRESS=docker.io
FROM $SOURCE_CONTAINER_REGISTRY_ADDRESS/arm64v8/node:14-slim

WORKDIR /app/

COPY package*.json ./
COPY NOTICE.txt ./

RUN npm install --production

COPY *.js ./
COPY codecs ./codecs

USER node

EXPOSE 8080

CMD ["node", "app.js"]
