// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

//------------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is re-generated.
//------------------------------------------------------------------------------

#nullable enable

namespace LoRaWan
{
    using System;
    using System.Buffers.Binary;

    readonly partial struct DevEui : IEquatable<DevEui>, IFormattable
    {
        public const int Size = sizeof(ulong);

        readonly ulong value;

        public DevEui(ulong value) => this.value = value;

        public ulong AsUInt64 => this.value;

        public bool Equals(DevEui other) => this.value == other.value;
        public override bool Equals(object? obj) => obj is DevEui other && this.Equals(other);
        public override int GetHashCode() => this.value.GetHashCode();

        public override string ToString() => ToString("G", null);

        public static bool operator ==(DevEui left, DevEui right) => left.Equals(right);
        public static bool operator !=(DevEui left, DevEui right) => !left.Equals(right);

        public static DevEui Read(ReadOnlySpan<byte> buffer) =>
            new(BinaryPrimitives.ReadUInt64LittleEndian(buffer));

        public static DevEui Read(ref ReadOnlySpan<byte> buffer)
        {
            var result = Read(buffer);
            buffer = buffer[Size..];
            return result;
        }

        public Span<byte> Write(Span<byte> buffer)
        {
            BinaryPrimitives.WriteUInt64LittleEndian(buffer, this.value);
            return buffer[Size..];
        }

        public static DevEui Parse(ReadOnlySpan<char> input) =>
            TryParse(input, out var result) ? result : throw new FormatException();

        public static DevEui Parse(ReadOnlySpan<char> input, string? format) =>
            TryParse(input, format, out var result) ? result : throw new FormatException();

        public static bool TryParse(ReadOnlySpan<char> input, out DevEui result) => TryParse(input, "G", out result);

        public static bool TryParse(ReadOnlySpan<char> input, string? format, out DevEui result)
        {
            var (success, tempResult) = format?.ToLowerInvariant() switch
            {
                null or "g" or "d"  => TryParseHex(input, '-'),
                "e"                 => TryParseHex(input, ':'),
                "n"                 => TryParseHex(input, null),
                "i"                 => TryParseId6(input),
                _                   => (false, default)
            };

            result = tempResult;
            return success;

            static (bool, DevEui) TryParseHex(ReadOnlySpan<char> input, char? separator) =>
                Hexadecimal.TryParse(input, out var raw, separator) ? (true, new DevEui(raw)) : (false, default);

            static (bool, DevEui) TryParseId6(ReadOnlySpan<char> input) =>
                Id6.TryParse(input, out var raw) ? (true, new DevEui(raw)) : (false, default);
        }

        public string ToString(string? format, IFormatProvider? formatProvider) => Eui.Format(this.value, format);
    }

    readonly partial struct JoinEui : IEquatable<JoinEui>, IFormattable
    {
        public const int Size = sizeof(ulong);

        readonly ulong value;

        public JoinEui(ulong value) => this.value = value;

        public ulong AsUInt64 => this.value;

        public bool Equals(JoinEui other) => this.value == other.value;
        public override bool Equals(object? obj) => obj is JoinEui other && this.Equals(other);
        public override int GetHashCode() => this.value.GetHashCode();

        public override string ToString() => ToString("G", null);

        public static bool operator ==(JoinEui left, JoinEui right) => left.Equals(right);
        public static bool operator !=(JoinEui left, JoinEui right) => !left.Equals(right);

        public static JoinEui Read(ReadOnlySpan<byte> buffer) =>
            new(BinaryPrimitives.ReadUInt64LittleEndian(buffer));

        public static JoinEui Read(ref ReadOnlySpan<byte> buffer)
        {
            var result = Read(buffer);
            buffer = buffer[Size..];
            return result;
        }

        public Span<byte> Write(Span<byte> buffer)
        {
            BinaryPrimitives.WriteUInt64LittleEndian(buffer, this.value);
            return buffer[Size..];
        }

        public static JoinEui Parse(ReadOnlySpan<char> input) =>
            TryParse(input, out var result) ? result : throw new FormatException();

        public static JoinEui Parse(ReadOnlySpan<char> input, string? format) =>
            TryParse(input, format, out var result) ? result : throw new FormatException();

        public static bool TryParse(ReadOnlySpan<char> input, out JoinEui result) => TryParse(input, "G", out result);

        public static bool TryParse(ReadOnlySpan<char> input, string? format, out JoinEui result)
        {
            var (success, tempResult) = format?.ToLowerInvariant() switch
            {
                null or "g" or "d"  => TryParseHex(input, '-'),
                "e"                 => TryParseHex(input, ':'),
                "n"                 => TryParseHex(input, null),
                "i"                 => TryParseId6(input),
                _                   => (false, default)
            };

            result = tempResult;
            return success;

            static (bool, JoinEui) TryParseHex(ReadOnlySpan<char> input, char? separator) =>
                Hexadecimal.TryParse(input, out var raw, separator) ? (true, new JoinEui(raw)) : (false, default);

            static (bool, JoinEui) TryParseId6(ReadOnlySpan<char> input) =>
                Id6.TryParse(input, out var raw) ? (true, new JoinEui(raw)) : (false, default);
        }

        public string ToString(string? format, IFormatProvider? formatProvider) => Eui.Format(this.value, format);
    }

    readonly partial struct StationEui : IEquatable<StationEui>, IFormattable
    {
        public const int Size = sizeof(ulong);

        readonly ulong value;

        public StationEui(ulong value) => this.value = value;

        public ulong AsUInt64 => this.value;

        public bool Equals(StationEui other) => this.value == other.value;
        public override bool Equals(object? obj) => obj is StationEui other && this.Equals(other);
        public override int GetHashCode() => this.value.GetHashCode();

        public override string ToString() => ToString("G", null);

        public static bool operator ==(StationEui left, StationEui right) => left.Equals(right);
        public static bool operator !=(StationEui left, StationEui right) => !left.Equals(right);

        public static StationEui Read(ReadOnlySpan<byte> buffer) =>
            new(BinaryPrimitives.ReadUInt64LittleEndian(buffer));

        public static StationEui Read(ref ReadOnlySpan<byte> buffer)
        {
            var result = Read(buffer);
            buffer = buffer[Size..];
            return result;
        }

        public Span<byte> Write(Span<byte> buffer)
        {
            BinaryPrimitives.WriteUInt64LittleEndian(buffer, this.value);
            return buffer[Size..];
        }

        public static StationEui Parse(ReadOnlySpan<char> input) =>
            TryParse(input, out var result) ? result : throw new FormatException();

        public static StationEui Parse(ReadOnlySpan<char> input, string? format) =>
            TryParse(input, format, out var result) ? result : throw new FormatException();

        public static bool TryParse(ReadOnlySpan<char> input, out StationEui result) => TryParse(input, "G", out result);

        public static bool TryParse(ReadOnlySpan<char> input, string? format, out StationEui result)
        {
            var (success, tempResult) = format?.ToLowerInvariant() switch
            {
                null or "g" or "d"  => TryParseHex(input, '-'),
                "e"                 => TryParseHex(input, ':'),
                "n"                 => TryParseHex(input, null),
                "i"                 => TryParseId6(input),
                _                   => (false, default)
            };

            result = tempResult;
            return success;

            static (bool, StationEui) TryParseHex(ReadOnlySpan<char> input, char? separator) =>
                Hexadecimal.TryParse(input, out var raw, separator) ? (true, new StationEui(raw)) : (false, default);

            static (bool, StationEui) TryParseId6(ReadOnlySpan<char> input) =>
                Id6.TryParse(input, out var raw) ? (true, new StationEui(raw)) : (false, default);
        }

        public string ToString(string? format, IFormatProvider? formatProvider) => Eui.Format(this.value, format);
    }
}
