name: 'Power ON or DEALLOCATE a specific Azure VM'
description: 'This action either powers on or powers off (deallocates) a specific Azure VM'

inputs:
  POWER_SWITCH:
    description: 'Turn ON or OFF the VM'
    required: true
    type: boolean
  AZURE_VM_NAME:
    description: 'Name of the VM'
    required: true
  AZURE_RG_NAME:
    description: 'Resource Group where the VM lives'
    required: true
  AZURE_SP_CLIENTID:
    description: 'Service Principal ClientID'
    required: true
  AZURE_SP_SECRET:
    description: 'Service Principal Secret'
    required: true
  AZURE_TENANTID:
    description: 'Service Principal TenantID'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Login with az CLI"
      shell: bash
      run: |
        az login --service-principal -u ${{ inputs.AZURE_SP_CLIENTID }} -p ${{ inputs.AZURE_SP_SECRET }} --tenant ${{ inputs.AZURE_TENANTID }}
    
    - name: "Deallocate VM"
      shell: bash
      if: ${{ !inputs.POWER_SWITCH }}
      run: | 
        az vm deallocate --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ inputs.AZURE_RG_NAME }} --no-wait 

    - name: "Start VM"
      shell: bash
      if: ${{ inputs.POWER_SWITCH }}
      run: | 
        az vm start --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ inputs.AZURE_RG_NAME }} --no-wait 