name: 'Power ON or DEALLOCATE a specific Azure VM'
description: 'This action either powers on or powers off (deallocates) a specific Azure VM'

inputs:
  POWER_SWITCH:
    description: 'Turn ON or OFF the VM'
    required: true
    type: boolean
  AZURE_VM_NAME:
    description: 'Name of the VM'
    required: true
  AZURE_RG_NAME:
    description: 'Resource Group where the VM lives'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Deallocate VM"
      shell: bash
      if: inputs.POWER_SWITCH == 'false'
      run: | 
        az vm deallocate --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ inputs.AZURE_RG_NAME }} --no-wait 

    - name: "Start VM"
      shell: bash
      if: inputs.POWER_SWITCH == 'true'
      run: | 
        az vm start --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ inputs.AZURE_RG_NAME }} --no-wait 