# action.yml
name: 'IoT Edge Dev'
description: 'Iot Edge cli'
inputs:
  deployment_file_name:
    description: 'File path of the manifest file'
    required: true
  folder_path:
    description: 'Folder path of the manifest file'
    required: true
  architecture:
    description: 'Platform to target'
    required: true
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.deployment_file_name }}
    - ${{ inputs.folder_path }}
    - ${{ inputs.architecture }}
