FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY ./Logger ./Logger
COPY ./LoRaWan.NetworkServer ./LoRaWan.NetworkServer
COPY ./LoRaWanNetworkSrvModule ./LoRaWanNetworkSrvModule
COPY ./LoraTools ./LoraTools

WORKDIR ./LoRaWanNetworkSrvModule
RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1.5-runtime-stretch-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/LoRaWanNetworkSrvModule/out/* ./
ENTRYPOINT ["dotnet", "LoRaWanNetworkSrvModule.dll"]