FROM mcr.microsoft.com/dotnet/sdk:5.0-bullseye-slim-amd64 AS build-env

WORKDIR /build
COPY Directory.Build.props ./
COPY AssemblyInfo.cs ./
COPY .editorconfig ./
COPY global.json ./

WORKDIR /build/LoRaEngine/modules/LoRaWanNetworkSrvModule
COPY ["LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule.csproj", "LoRaWanNetworkSrvModule/"]
COPY ["LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaWan.NetworkServer.csproj", "LoRaWan.NetworkServer/"]
COPY ["LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/LoRaWan.csproj", "LoRaWan/"]
COPY ["LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaTools.csproj", "LoraTools/"]
COPY ["LoRaEngine/modules/LoRaWanNetworkSrvModule/Logger/Logger.csproj", "Logger/"]
RUN dotnet restore "LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule.csproj"

COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/Logger Logger
COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools LoraTools
COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer LoRaWan.NetworkServer
COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule LoRaWanNetworkSrvModule
COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan LoRaWan

WORKDIR /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule

RUN dotnet publish "LoRaWanNetworkSrvModule.csproj" -c Release -o out --no-restore --self-contained false

FROM mcr.microsoft.com/dotnet/aspnet:3.1-bullseye-slim
WORKDIR /app
COPY --from=build-env /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule/out/* ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "LoRaWanNetworkSrvModule.dll"]
