FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim-amd64 AS build-env

WORKDIR /build
COPY Directory.Build.props ./
COPY AssemblyInfo.cs ./
COPY .editorconfig ./
COPY global.json ./

WORKDIR /build/LoRaEngine/modules
COPY ["LoRaEngine/modules/LoRaWan.NetworkServerDiscovery/LoRaWan.NetworkServerDiscovery.csproj", "LoRaWan.NetworkServerDiscovery/"]

WORKDIR /build/LoRaEngine/modules/LoRaWanNetworkSrvModule
COPY ["LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule.csproj", "LoRaWanNetworkSrvModule/"]
COPY ["LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaWan.NetworkServer.csproj", "LoRaWan.NetworkServer/"]
COPY ["LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan/LoRaWan.csproj", "LoRaWan/"]
COPY ["LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/LoRaTools.csproj", "LoraTools/"]
RUN dotnet restore "LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule.csproj"

COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools LoraTools
COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer LoRaWan.NetworkServer
COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule LoRaWanNetworkSrvModule
COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan LoRaWan

WORKDIR /build/LoRaEngine/modules
COPY ./LoRaEngine/modules/LoRaWan.NetworkServerDiscovery LoRaWan.NetworkServerDiscovery

WORKDIR /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule

RUN dotnet publish "LoRaWanNetworkSrvModule.csproj" -c Release -o out --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm64v8
WORKDIR /app
COPY --from=build-env /build/LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWanNetworkSrvModule/out/* ./
COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/start.sh ./
COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/appsettings.json ./
COPY ./LoRaEngine/modules/LoRaWanNetworkSrvModule/NOTICE.txt ./
COPY LICENSE ./
RUN chmod +x ./start.sh
ENTRYPOINT ["./start.sh"]
