#This docker builds a container for the LoRa Basics station on arm32 architecture

FROM amd64/debian:buster as build
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y apt-utils build-essential gcc-arm-linux-gnueabihf
RUN git clone --branch v2.0.5 --single-branch --depth 1 https://github.com/lorabasics/basicstation.git
RUN mkdir -p ~/toolchain-rpi/bin/
RUN ln -s /usr/bin/arm-linux-gnueabihf-gcc ~/toolchain-rpi/bin/arm-linux-gnueabihf-gcc
RUN ln -s /usr/bin/arm-linux-gnueabihf-ld ~/toolchain-rpi/bin/arm-linux-gnueabihf-ld
RUN ln -s /usr/bin/arm-linux-gnueabihf-ar ~/toolchain-rpi/bin/arm-linux-gnueabihf-ar
RUN ln -s /usr/bin/arm-linux-gnueabihf-objdump ~/toolchain-rpi/bin/arm-linux-gnueabihf-objdump
RUN ln -s /usr/bin/arm-linux-gnueabihf-objcopy ~/toolchain-rpi/bin/arm-linux-gnueabihf-objcopy
WORKDIR /basicstation

# make standard version
RUN make platform=rpi variant=std
RUN mkdir built && cp ./build-rpi-std/bin/station ./built/station.std

# clean before making spi speed 2 version
RUN make platform=rpi variant=std clean
# make spi speed 2 version
RUN sed -i "s|8000000|2000000|g" /basicstation/deps/lgw/platform-rpi/libloragw/src/loragw_spi.native.c
RUN make platform=rpi variant=std
RUN cp ./build-rpi-std/bin/station ./built/station.spispeed2

FROM arm32v7/debian:buster
WORKDIR /basicstation
COPY --from=build /basicstation/deps/lgw/platform-rpi/reset_lgw.sh .
COPY --from=build /basicstation/built/* .
COPY LoRaEngine/modules/LoRaBasicsStationModule/station.conf .
COPY LoRaEngine/modules/LoRaBasicsStationModule/helper-functions.sh .
COPY LoRaEngine/modules/LoRaBasicsStationModule/start_basicsstation.sh .
COPY LICENSE .
COPY ./LoRaEngine/modules/LoRaBasicsStationModule/NOTICE.txt .
RUN chmod +x ./start_basicsstation.sh
ENTRYPOINT ["./start_basicsstation.sh"]
