FROM microsoft/dotnet:2.1-sdk-stretch

ENV VSTS_POOL=default VSTS_AGENT=myAgent

# Install curl, wget and git
RUN apt-get update && apt-get install -y \
curl \
wget \
git
 
# Download compiles vsts-agent
RUN curl https://vstsagentpackage.azureedge.net/agent/2.142.1/vsts-agent-linux-x64-2.142.1.tar.gz -o vsts-agent.tar.gz
RUN mkdir mkdir -p vsts-agent/_diag && chmod o+w ./vsts-agent
RUN tar xzf vsts-agent.tar.gz -C ./vsts-agent
 
# install node
RUN curl -sL https://deb.nodesource.com/setup_8.x
RUN apt-get install -y nodejs

COPY vsts.sh .

ENTRYPOINT [ "/bin/bash", "./vsts.sh" ]