FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

WORKDIR /build/Samples/DecoderSample/
COPY ./Samples/DecoderSample ./

RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim-arm32v7 AS runtime
WORKDIR /app
COPY --from=build-env /build/Samples/DecoderSample/out/* ./
ENTRYPOINT ["dotnet", "SensorDecoderModule.dll"]
