FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

WORKDIR /build/Samples/DecoderSample/
COPY ./Samples/DecoderSample ./

RUN dotnet restore

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7 AS runtime
WORKDIR /app
COPY --from=build-env /build/Samples/DecoderSample/out/* ./
ENTRYPOINT ["dotnet", "SensorDecoderModule.dll"]
