name: publish-docs-dev
on:
  push:
    branches:
      - docs/main
  # workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x      
      - run: git fetch origin gh-pages --depth=1
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: | 
          pip install mkdocs-material
          pip install mike
          pip install mdx_truly_sane_lists
      - run: | 
          mike deploy --push dev
          mike list