name: Set POWER for Azure VM

on:
  # this is a template that can be called from other pipelines
  workflow_call:
    inputs:
      POWER_SWITCH:
        required: true
        type: string # expects string literal 'ON' or 'OFF', doesn't work with boolean
      AZURE_VM_NAME:
        required: true
        type: string
      AZURE_RG_NAME:
        required: true
        type: string
    secrets: 
      # a template cannot directly access secrets, 
      # they have to be passed in from the outside.
      # see https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
      AZURE_SP_CLIENTID:
        required: true
      AZURE_SP_SECRET:
        required: true
      AZURE_TENANTID:
        required: true
        
jobs:
  power_azure_vm:
    runs-on: ubuntu-latest # see https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#using-github-hosted-runners
    steps:
      - name: "Login with az CLI"
        run: |
          az login --service-principal -u ${{ secrets.AZURE_SP_CLIENTID }} --p ${{ secrets.AZURE_SP_SECRET }} --tenant ${{ secrets.AZURE_TENANTID }}
      
      - name: "Deallocate VM (if requested)"
        if: ${{ inputs.POWER == 'OFF' }}
        run: | 
          az vm deallocate --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ inputs.AZURE_RG_NAME }} --no-wait 

      - name: "Start VM (if requested)"
        if: ${{ inputs.POWER == 'ON' }}
        run: | 
          az vm start --name ${{ inputs.AZURE_VM_NAME }} --resource-group ${{ inputs.AZURE_RG_NAME }} --no-wait 