name: 'Test Report'
on:
  workflow_run:
    workflows: ['LoRa CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    permissions:
      checks: read/write 
      pull requests: read/write 
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: "*results"
        name: UnitTestResults
        path: '*.trx'
        reporter: dotnet-trx
