name: 'Test Report'
on:
  workflow_run:
    workflows: ['LoRa CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    permissions:
      checks: write 
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: unit-test-results            # artifact name
        name: UnitTestResults                  # Name of the check run which will be created
        path: '*.trx'                     # Path to test results (inside artifact .zip)
        reporter: dotnet-trx            # Format of test results